### ISSUE TITLE
Segmentation fault with CLI

### ISSUE THREAD

**Issue by gmanepalli-mlabs** [sourcemeta/jsonschema#182]
I receive a segmentation fault when I try to validate a schema.

$jsonschema metaschema OMC-JSON-v2.0.schema.json
zsh: segmentation fault  /opt/homebrew/bin/jsonschema metaschema OMC-JSON-v2.0.schema.json

The verbose option (-v) to the command does not provide any other information. I am running MacOS and I just installed jsonschema using brew.

If I try to validate an instance against this schema (jsonschema validate...), the process hangs. However, lint/frame/identify commands work - indicating the program is able to process the schema at least on a few occassions.

The schema is publicly available here: https://movielabs.com/omc/json/schema/v2.0

Any thoughts on what I should do next? Thanks.

**Comment by jviotti** [comment]
Hi @gmanepalli-mlabs ,

Thanks for reaching out. Interesting problem and I can definitely reproduce. Please allow me to debug further and get back to you soon! Definitely looks like a bug somewhere

**Comment by jviotti** [comment]
@gmanepalli-mlabs The `metaschema` command error was a silly overlook from our side while processing validation error messages. I just sent a PR fixing it! Our existing test suite for the `metaschema` command was a bit weak and it went under the radar for a while.

The hang is less obvious. I think you found a bug in Blaze (https://github.com/sourcemeta/blaze), our experimental new schema compiler. We are stress test it against schemas with more than >8000 lines, so I'm not concerned about the OMC JSON size, but there might be something else causing the infinite loop, probably on the heavy static analysis we perform during compilation.

Let me continue digging into that one tomorrow and hopefully release a new version by then! 🙏🏻

**Comment by gmanepalli-mlabs** [comment]
Thank you so much for digging into this and that too promptly. `metaschema` command is more useful for us than `validate` (because we have our own instance validators).

**Comment by jviotti** [comment]
Ah, great @gmanepalli-mlabs ! Then check out v4.1.4 on Homebrew (released just now: https://github.com/sourcemeta/jsonschema/releases/tag/v4.1.4). That should solve the `metaschema` issue while I fix the `validate` one tomorrow. Looks like the latter is due to our static analysis logic not detecting one of the schema's recursive cases correctly (and infinitely unrolling the references).

Also, as a TSC member of JSON Schema, I would love to connect and see how the JSON Schema organisation can support MovieLabs. Maybe a virtual coffee chat this week or the next? :)

**Comment by gmanepalli-mlabs** [comment]
4.1.4 fixed `metaschema` command. Thanks. Please let me know when `validate` command is working (to close the ticket).

Let me circle back to you regarding the call. We could benefit from your input on our schema design/approach.

**Comment by jviotti** [comment]
@gmanepalli-mlabs 

> Let me circle back to you regarding the call. We could benefit from your input on our schema design/approach.

Sounds great. It'd be a pleasure to help out!

**Comment by jviotti** [comment]
As a status update on this, it's not an infinite loop, but the compiler takes a VERY LONG time pre-compiling this specific schema by overly unrolling static references (for performance reasons). If you wait long enough, the compiled result is quite fast (which is why we pre-compile). However, definitely not acceptable. We are exploring ways to optimise the compiler to at least bring it down to a reasonable number.

**Comment by jviotti** [comment]
@gmanepalli-mlabs It took us a while more to figure it out, but we have a PR that speeds up the compilation time for the OMC schema by orders of magnitude, leading to both compilation + validation in ~1.5s on my MBP M3 Pro. 

Interestingly enough, the problem is that OMC is one of the most highly recursive schemas we've seen. Our JSON Schema compiler works by aggressively preprocessing schemas into an intermediate representation that results in ultra high performance validation (we are publishing a benchmark paper showing Blaze being way faster than any other existing validator). However, for this compilation process, it assumes it can start independently precompiling at least some schema leaves. But with OMC, almost all of the internally referenced schemas end up referencing everything else, creating a hugely circular schema that the compiler was choking on!

I'll release a new version of the CLI with the fix in a bit for you to give it a shot.

**Comment by jviotti** [comment]
> Right, the structure of a schema document is orthogonal to the dependency graph of subschemas. Our schema is an evolving document as we continue to cover more and more media production scenarios. We have to carefully tread the line between readability and reliability. Many users unknown to us look at our schema. We do not want to surprise them with wholesale changes in structure in every release.

For sure. I'm not critiquing the schema architecture. It seems to make sense for what it defines and it was a fun stress test for our compiler 😅 

That said, have you looked into splitting the monolithic schema into many independent schemas that refer to each other? It could make it easier to understand, and unit test (i.e. with https://github.com/sourcemeta/jsonschema/blob/main/docs/test.markdown), and you can still provide a single compiled schema by making use of bundling (https://github.com/sourcemeta/jsonschema/blob/main/docs/bundle.markdown).

Let me know how your testing goes and would definitely love to talk sometime soon! Finally, If you end up liking the CLI and you feel like it, we would love to get a testimonial from you guys (https://github.com/sourcemeta/jsonschema/tree/main?tab=readme-ov-file#what-our-users-are-saying).
